# Generated by Django 3.2 on 2021-11-04 01:11

from django.db import migrations, models
import django.db.models.deletion
import sqlphile.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('email_verified', models.BooleanField(blank=True, default=False)),
                ('nick_name', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=32, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('birthday', models.CharField(blank=True, max_length=16, null=True)),
                ('lev', models.CharField(choices=[('guest', 'guest'), ('user', 'user'), ('staff', 'staff')], default='user', max_length=16)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'firebase_user',
                'managed': True,
                'proxy': False,
            },
            bases=(sqlphile.model.AbstractModel, models.Model),
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=16)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebase_vue.user')),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'User Logs',
                'db_table': 'firebase_user_log',
                'managed': True,
                'proxy': False,
            },
            bases=(sqlphile.model.AbstractModel, models.Model),
        ),
    ]
