# Generated by Django 3.2 on 2021-11-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_vue', '0003_auto_20211104_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
    ]
