#!/bin/sh
# chkconfig: 123456 90 10
# TTS Server for Speech Synthesis
#

start() {
    skitaid.py &
    echo "Skitaid App Engine Started."
}
 
stop() {
    pidfile="/var/lock/skitaid/pid"
    pid=`cat $pidfile`
    #pid=`ps -ef | grep '/usr/local/bin/skitaid.py' | awk '{ print $2 }'`
    #echo $pid
    kill $pid
    sleep 2
    echo "Skitai App Engine Killed."
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/skitaid {start|stop|restart}"
    exit 1
esac
exit 0
