#!/bin/sh

### BEGIN INIT INFO
# Provides:          skitaid
# Required-Start:    $local_fs $network &syslog $named
# Required-Stop:     $local_fs $network &syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Skitai App Engine Service
### END INIT INFO

SNAME="Skitai App Engine"
check() {
    pidfile="/var/lock/skitaid/pid"
    if [ ! -f $pidfile ]
    then
        return 0
    fi

    pid1=`cat $pidfile`
    pid2=`ps -ef | grep '[/]usr/bin/python /usr/local/bin/skitaid.py' | awk '{ print $2 }'`
    if [ "$pid1" = "$pid2" ]
    then
        return 1
    else
        return 0
    fi
}

start() {
    check
    if [ $? -eq 0 ]
    then
        /usr/local/bin/skitaid.py &        
        echo "$SNAME started"
    else
        echo "$SNAME already started"
    fi  
}
 
stop() {
    check
    if [ $? -eq 1 ]
    then
        pidfile="/var/lock/skitaid/pid"
        pid=`cat $pidfile`
        echo "$SNAME stopping..."
        kill $pid
        while [ 1 -eq 1 ] 
	do 
		sleep 1
		check
		if [ $? -eq 0 ] 
		then
			break
		fi
	done
        echo "$SNAME stopped"
    else
        echo "$SNAME already stopped"
    fi  
}

status() {
    check
    if [ $? -eq 1 ]
    then
        echo "$SNAME running"
        return 1
    else
        echo "$SNAME stopped"
        return 0
    fi
}

case "$1" in
  start)
     start
     ;;
  stop)
     stop   
     ;;
  status)
    status
    ;;  
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: service skitaid {start|stop|restart|status}"
    exit 1
esac
exit 0

