# Generated by Django 3.2.9 on 2021-11-05 05:12

from django.db import migrations, models
import django.db.models.deletion
import sqlphile.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('video_url', models.CharField(max_length=1024)),
                ('callback_url', models.CharField(max_length=1024)),
                ('last_status', models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='new', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
                'db_table': 'transcription',
                'managed': True,
                'proxy': False,
            },
            bases=(sqlphile.model.AbstractModel, models.Model),
        ),
        migrations.CreateModel(
            name='TranscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=512, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcription.transcription')),
            ],
            options={
                'verbose_name': 'Transcription Log',
                'verbose_name_plural': 'Transcription Logs',
                'db_table': 'transcription_log',
                'managed': True,
                'proxy': False,
            },
            bases=(sqlphile.model.AbstractModel, models.Model),
        ),
    ]
