# Generated by Django 3.2.9 on 2021-11-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_auto_20211105_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='callback_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='video_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
