# Generated by Django 3.2.9 on 2021-11-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_auto_20211105_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='callback_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='video_url',
            field=models.TextField(),
        ),
    ]
