# Generated by Django 3.2.9 on 2021-11-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_auto_20211105_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='callback_url',
            new_name='callback_uri',
        ),
        migrations.RenameField(
            model_name='transcription',
            old_name='video_url',
            new_name='video_uri',
        ),
    ]
