# Generated by Django 3.2.9 on 2021-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0007_auto_20211105_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='last_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='transcriptionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], max_length=16),
        ),
    ]
