# Generated by Django 3.2.9 on 2021-11-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0008_auto_20211105_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='upload_path',
            field=models.CharField(default='asda', max_length=1024),
            preserve_default=False,
        ),
    ]
